/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Editorial Theme Colors
        "on-primary-fixed": "#1b1b1e",
        "surface-container": "#eeeeef",
        "primary-container": "#1b1b1e",
        "on-background": "#1a1c1d",
        "on-surface-variant": "#47464b",
        "on-secondary-container": "#626362",
        "tertiary-fixed": "#ffdad8",
        "outline": "#77767b",
        "accent-coral": "#FF6B6B",
        "secondary-container": "#e0dfdf",
        "ink-black": "#18181B",
        "on-primary": "#ffffff",
        "primary-fixed": "#e4e1e6",
        "on-primary-container": "#858387",
        "panel-white": "#FFFFFF",
        "surface-container-low": "#f3f3f4",
        "outline-variant": "#c8c5cb",
        "inverse-primary": "#c8c5ca",
        "on-tertiary-fixed-variant": "#8c1520",
        "border-subtle": "#F4F4F5",
        "primary-fixed-dim": "#c8c5ca",
        "inverse-surface": "#2f3132",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#47464a",
        "on-secondary-fixed-variant": "#464746",
        "surface-paper": "#FDFCFB",
        "inverse-on-surface": "#f0f1f2",
        "surface-bright": "#f9f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e9",
        "secondary-fixed-dim": "#c7c6c5",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#410006",
        "on-secondary": "#ffffff",
        "surface-tint": "#5f5e61",
        "surface-dim": "#dadadb",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1d",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2e2e3",
        "on-tertiary-container": "#e05456",
        "secondary-fixed": "#e3e2e1",
        "surface-variant": "#e2e2e3",
        "tertiary-fixed-dim": "#ffb3b0",
        "surface": "#f9f9fa",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-container": "#410006"
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        // Editorial radii
        'editorial-none': '0',
        'editorial-sm': '0.125rem',
        'editorial-md': '0.25rem',
        'editorial-lg': '0.5rem',
        'editorial-xl': '0.75rem',
      },
      spacing: {
        "margin-desktop": "64px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "gutter": "24px",
        "unit": "8px"
      },
      fontFamily: {
        jakarta: ["Plus Jakarta Sans", "sans-serif"],
        "editorial-display": ["Plus Jakarta Sans", "sans-serif"],
        "display-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-sm": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [],
}
